/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                      '#5b614d',
        'primary-dim':                  '#4f5542',
        'primary-fixed':                '#dfe5cc',
        'primary-fixed-dim':            '#d1d7be',
        'primary-container':            '#dfe5cc',
        'on-primary':                   '#f5fbe1',
        'on-primary-fixed':             '#3c422f',
        'on-primary-fixed-variant':     '#585e4a',
        'on-primary-container':         '#4e5441',

        'secondary':                    '#606751',
        'secondary-dim':                '#535b46',
        'secondary-fixed':              '#dee6ca',
        'secondary-fixed-dim':          '#d0d8bd',
        'secondary-container':          '#dee6ca',
        'on-secondary':                 '#ffffff',
        'on-secondary-fixed':           '#3b422e',
        'on-secondary-fixed-variant':   '#575e49',
        'on-secondary-container':       '#4d543f',

        'tertiary':                     '#885a30',
        'tertiary-dim':                 '#7a4f25',
        'tertiary-fixed':               '#fec38f',
        'tertiary-fixed-dim':           '#efb583',
        'tertiary-container':           '#fec38f',
        'on-tertiary':                  '#ffffff',
        'on-tertiary-fixed':            '#4d2a03',
        'on-tertiary-fixed-variant':    '#6f451d',
        'on-tertiary-container':        '#643c14',

        'background':                   '#FDFBF7',
        'on-background':                '#2c2c26',
        'surface':                      '#FDFBF7',
        'surface-bright':               '#FDFBF7',
        'surface-dim':                  '#EBE8DD',
        'surface-variant':              '#f2f0e4',
        'surface-tint':                 '#5b614d',
        'surface-container-lowest':     '#ffffff',
        'surface-container-low':        '#F7F4EE',
        'surface-container':            '#F1EFE6',
        'surface-container-high':       '#EFEDE4',
        'surface-container-highest':    '#E6E3D8',
        'on-surface':                   '#2c2c26',
        'on-surface-variant':           '#6D6B62',

        'outline':                      '#8B897D',
        'outline-variant':              '#d9d8cd',
        'inverse-surface':              '#1a1a17',
        'inverse-on-surface':           '#9f9d96',
        'inverse-primary':              '#f6fce2',

        'error':                        '#a54731',
        'error-dim':                    '#5c1202',
        'error-container':              '#fe8b70',
        'on-error':                     '#ffffff',
        'on-error-container':           '#742410',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
