"""add conditions column to analysis_results

Revision ID: cfa1616534cf
Revises: 5b23371c53eb
Create Date: 2026-04-24 09:49:59.886995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cfa1616534cf'
down_revision: Union[str, None] = '5b23371c53eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'conditions')
    # ### end Alembic commands ###
